
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "px4-legal"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size
# for accidental or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[db.pooler]
enabled = false
# Port to use for the local connection pooler.
port = 54329
# The maximum number of connections the pooler can open in each mode (transaction or session).
# Default is 15 which means 15 transaction connections and 15 session connections.
pool_size = 15
# How many connections to keep active and ready to use. This greatly effects performance and DB load.
# Default is 2. Set 0 to close and reopon connections as needed.
default_pool_size = 2
# How long to wait when connecting to a database before timing out.
connect_timeout_seconds = 30
# How long to wait when querying a database before timing out.
query_timeout_seconds = 120
# The maximum expected delay before a retry succeeds.
max_delay_seconds = 60
# Default behavior for prepared statements when using the connection pooler with transactions.
prepared_statements = true

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://localhost"
# Enable automatic migration checks
auto_check_migration = true

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true
# Allow/disallow managing auth configurations via the Studio UI; only respected in production
# environments.
enable_admin = false
# roles 
enable_roles = false
enable_roles_hint = true
enable_resource_role_permissions = true
enable_permissions = false
enable_user_attributes = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = false
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false

# Configure one of the supported SMS providers: `twilio`, `messagebird`, `textlocal`, `vonage`.
# [auth.sms.twilio]
# account_sid = ""
# message_service_sid = ""
# auth_token = ""

[auth.roles]
enable_password_metadata_defaults_mode = true

# Use an external OAuth provider. The full list of providers are: `apple`, `azure`, `bitbucket`,
# `discord`, `facebook`, `github`, `gitlab`, `google`, `keycloak`, `linkedin`, `notion`, `twitch`,
# `twitter`, `slack`, `spotify`, `workos`, `zoom`.
# [auth.external.apple]
# enabled = false
# client_id = ""
# secret = ""
# Additional scopes to request with the OAuth provider.
# scopes = ["user:email"]

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Configure one of the supported backends.
# [analytics.postgres]
# backend = "postgres"
# [analytics.custom]
# backend = "custom"
# host = "127.0.0.1"
# port = 5432
# connection_string = "postgres://..."
# db_schema = "postgres"
# name = "custom"

# Configure PostgREST.
[postgres]
# Extra Postgres extensions to include in the database. Requires cache refresh to apply.
# extensions = ["uuid-ossp", "pg_graphql"]

[edge_functions]
enabled = true
