// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yowihgrlmntraktvruve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlvd2loZ3JsbW50cmFrdHZydXZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MTE5NjYsImV4cCI6MjA1OTE4Nzk2Nn0.WAqzTUXPg3DdWl2bTA09GkOS643x0qQ5XjWyJ49Ry5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);